// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq0ROUbE_PPjn36SDEt78Y-hyNpd4X0qA',
    appId: '1:677556783334:web:2fd87a44d20b6acff25327',
    messagingSenderId: '677556783334',
    projectId: 'dizigurmesi-56d09',
    authDomain: 'dizigurmesi-56d09.firebaseapp.com',
    storageBucket: 'dizigurmesi-56d09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCqUywYe4pvCmT8EvBJQmxnlzMa56sH50',
    appId: '1:677556783334:android:90ff6cba72eda0d5f25327',
    messagingSenderId: '677556783334',
    projectId: 'dizigurmesi-56d09',
    storageBucket: 'dizigurmesi-56d09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGGakNC51RRlPl8I7llY50nGyaiHQoask',
    appId: '1:677556783334:ios:ee700e0bd708ecfef25327',
    messagingSenderId: '677556783334',
    projectId: 'dizigurmesi-56d09',
    storageBucket: 'dizigurmesi-56d09.appspot.com',
    iosBundleId: 'com.example.dizigurmesi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGGakNC51RRlPl8I7llY50nGyaiHQoask',
    appId: '1:677556783334:ios:ee700e0bd708ecfef25327',
    messagingSenderId: '677556783334',
    projectId: 'dizigurmesi-56d09',
    storageBucket: 'dizigurmesi-56d09.appspot.com',
    iosBundleId: 'com.example.dizigurmesi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq0ROUbE_PPjn36SDEt78Y-hyNpd4X0qA',
    appId: '1:677556783334:web:86a83172b16b7b23f25327',
    messagingSenderId: '677556783334',
    projectId: 'dizigurmesi-56d09',
    authDomain: 'dizigurmesi-56d09.firebaseapp.com',
    storageBucket: 'dizigurmesi-56d09.appspot.com',
  );
}
